import Link from "next/link";

export function SiteFooter() {
  return (
    <footer className="mt-20 border-t border-white/10 py-8 text-center text-sm text-white/50">
      <div className="mx-auto max-w-4xl px-5">
        <p>
          PalmInsight is for entertainment and self-reflection. Readings are
          generated by an AI model and are not predictions of the future.
        </p>
        <div className="mt-3 flex flex-wrap items-center justify-center gap-4">
          <Link href="/privacy" className="hover:text-white/80">
            Privacy
          </Link>
          <span aria-hidden>·</span>
          <Link href="/scan" className="hover:text-white/80">
            Scan your palm
          </Link>
          <span aria-hidden>·</span>
          <span>© {new Date().getFullYear()} PalmInsight</span>
        </div>
        <p className="mt-3 text-xs text-white/40">
          Designed &amp; developed by{" "}
          <a
            href="https://ankursingh.site"
            target="_blank"
            rel="noopener noreferrer"
            className="text-cosmic-300 hover:text-cosmic-200 hover:underline"
          >
            ankursingh.site
          </a>
        </p>
      </div>
    </footer>
  );
}
