// Centralized runtime configuration + capability flags.

export const config = {
  baseUrl:
    process.env.NEXT_PUBLIC_BASE_URL?.replace(/\/$/, "") ||
    "http://localhost:3000",

  premiumPriceCents: Number(process.env.PREMIUM_PRICE_CENTS || 500),
  premiumCurrency: (process.env.PREMIUM_CURRENCY || "usd").toLowerCase(),

  // ONE switch controls everything:
  //   POLAR_LIVE=false (or unset) → TEST mode  (sandbox, fake cards, no real charges)
  //   POLAR_LIVE=true            → REAL mode   (production, real money)
  // The matching token/product/webhook are picked automatically per mode, so
  // you never have to swap individual values — just flip POLAR_LIVE.
  polar: (() => {
    const live = process.env.POLAR_LIVE === "true";
    const pick = (liveVal?: string, testVal?: string, legacy?: string) =>
      (live ? liveVal : testVal) || legacy || "";
    return {
      live,
      server: (live ? "production" : "sandbox") as "production" | "sandbox",
      accessToken: pick(
        process.env.POLAR_LIVE_ACCESS_TOKEN,
        process.env.POLAR_SANDBOX_ACCESS_TOKEN,
        process.env.POLAR_ACCESS_TOKEN
      ),
      productId: pick(
        process.env.POLAR_LIVE_PRODUCT_ID,
        process.env.POLAR_SANDBOX_PRODUCT_ID,
        process.env.POLAR_PRODUCT_ID
      ),
      webhookSecret: pick(
        process.env.POLAR_LIVE_WEBHOOK_SECRET,
        process.env.POLAR_SANDBOX_WEBHOOK_SECRET,
        process.env.POLAR_WEBHOOK_SECRET
      ),
    };
  })(),

  supabase: {
    url: process.env.NEXT_PUBLIC_SUPABASE_URL || "",
    anonKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "",
    serviceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY || "",
  },

  // AI vision providers. The reading is generated by actually looking at the
  // uploaded palm image. Free readings use a cheap model; paid Deep Reports use
  // the most capable model ("full potential"). All three providers are used as
  // a fallback chain so a single outage never breaks checkout/reads.
  ai: {
    anthropicKey: process.env.ANTHROPIC_API_KEY || "",
    openaiKey: process.env.OPENAI_API_KEY || "",
    geminiKey: process.env.GEMINI_API_KEY || "",
    // Overridable model ids (sensible defaults baked in lib/ai/palmVision.ts).
    anthropicCheap: process.env.AI_ANTHROPIC_CHEAP || "claude-haiku-4-5",
    anthropicPro: process.env.AI_ANTHROPIC_PRO || "claude-opus-4-8",
    openaiCheap: process.env.AI_OPENAI_CHEAP || "gpt-4o-mini",
    openaiPro: process.env.AI_OPENAI_PRO || "gpt-4o",
    geminiCheap: process.env.AI_GEMINI_CHEAP || "gemini-2.0-flash",
    geminiPro: process.env.AI_GEMINI_PRO || "gemini-2.0-flash",
  },

  unlockSecret: process.env.UNLOCK_TOKEN_SECRET || "dev-only-change-me",

  // Daily-horoscope email delivery (Resend). Optional.
  email: {
    resendKey: process.env.RESEND_API_KEY || "",
    from: process.env.EMAIL_FROM || "PalmInsight <onboarding@resend.dev>",
    replyTo: process.env.EMAIL_REPLY_TO || "",
    cronSecret: process.env.CRON_SECRET || "",
  },
};

/** True when email delivery (Resend) is configured. */
export const emailEnabled = Boolean(config.email.resendKey);

/**
 * True when real Polar billing is configured (otherwise mock checkout).
 * Requires both an organization access token and the Deep Report product id.
 */
export const polarEnabled = Boolean(
  config.polar.accessToken && config.polar.productId
);

/** True when Supabase is configured (otherwise in-memory store). */
export const supabaseEnabled = Boolean(
  config.supabase.url && config.supabase.serviceRoleKey
);

/** True when at least one AI vision provider is configured. */
export const aiEnabled = Boolean(
  config.ai.anthropicKey || config.ai.openaiKey || config.ai.geminiKey
);

export function priceLabel(): string {
  const amount = (config.premiumPriceCents / 100).toFixed(
    config.premiumPriceCents % 100 === 0 ? 0 : 2
  );
  const symbol = config.premiumCurrency === "usd" ? "$" : "";
  return `${symbol}${amount}`;
}
