import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";
import { config, aiEnabled } from "../config";
import type { LineKey } from "../types";

// ---------------------------------------------------------------------------
// AI palm-line vision.
//
// The reading is generated by ACTUALLY LOOKING at the uploaded palm photo with
// a vision LLM, so different palms produce different readings. We use a tiered,
// multi-provider fallback chain:
//
//   • Free reading  → cheapest capable model  (cost saving)
//   • Paid Deep Report → most capable model    (full potential for paying users)
//
// All three providers (Gemini, OpenAI, Anthropic) are tried in order; the first
// that succeeds wins, so a single provider outage never breaks a reading.
//
// The geometry/overlay of the four lines still comes from MediaPipe landmarks
// (lib/palmistry.ts); this module supplies the *interpretation* of what the
// model sees in the actual image.
// ---------------------------------------------------------------------------

const LineReadingSchema = z.object({
  key: z.enum(["life", "heart", "head", "fate"]),
  pattern: z.string(),
  confidence: z.number(),
  summary: z.string(),
  interpretation: z.array(z.string()),
});

const ReportSectionSchema = z.object({
  title: z.string(),
  body: z.array(z.string()),
});

const HighlightsSchema = z.object({
  archetype: z.string(),
  luckyNumber: z.string(),
  luckyColor: z.string(),
  luckyDay: z.string(),
});

const ReportSchema = z.object({
  highlights: HighlightsSchema,
  destiny: ReportSectionSchema,
  career: ReportSectionSchema,
  wealth: ReportSectionSchema,
  love: ReportSectionSchema,
  marriage: ReportSectionSchema,
  children: ReportSectionSchema,
});

const VisionResultSchema = z.object({
  // true ONLY when the image clearly shows a human palm with readable lines.
  isPalm: z.boolean(),
  // when isPalm is false, a short friendly reason to show the user; else "".
  reason: z.string(),
  lines: z.array(LineReadingSchema),
  report: ReportSchema.optional(),
});

export type VisionLineReading = z.infer<typeof LineReadingSchema>;
export type VisionResult = z.infer<typeof VisionResultSchema>;

// JSON Schema given to the models (structured-output constrained where supported).
function jsonSchema(includeReport: boolean) {
  const lineItem = {
    type: "object",
    additionalProperties: false,
    properties: {
      key: { type: "string", enum: ["life", "heart", "head", "fate"] },
      pattern: { type: "string", description: "e.g. 'Long & Deep', 'Curved with branches'" },
      confidence: { type: "integer", description: "0-100 confidence in this reading" },
      summary: { type: "string", description: "one-line headline" },
      interpretation: { type: "array", items: { type: "string" } },
    },
    required: ["key", "pattern", "confidence", "summary", "interpretation"],
  };
  const section = {
    type: "object",
    additionalProperties: false,
    properties: {
      title: { type: "string" },
      body: { type: "array", items: { type: "string" } },
    },
    required: ["title", "body"],
  };
  const properties: Record<string, unknown> = {
    isPalm: { type: "boolean", description: "true ONLY if the image clearly shows a human palm with visible palm lines" },
    reason: { type: "string", description: "if isPalm is false, a short friendly reason for the user; otherwise an empty string" },
    lines: { type: "array", items: lineItem },
  };
  const required = ["isPalm", "reason", "lines"];
  if (includeReport) {
    const highlights = {
      type: "object",
      additionalProperties: false,
      properties: {
        archetype: { type: "string", description: "a catchy 2-4 word palm personality type, e.g. 'The Visionary Builder'" },
        luckyNumber: { type: "string" },
        luckyColor: { type: "string" },
        luckyDay: { type: "string", description: "a day of the week" },
      },
      required: ["archetype", "luckyNumber", "luckyColor", "luckyDay"],
    };
    properties.report = {
      type: "object",
      additionalProperties: false,
      properties: {
        highlights,
        destiny: section,
        career: section,
        wealth: section,
        love: section,
        marriage: section,
        children: section,
      },
      required: ["highlights", "destiny", "career", "wealth", "love", "marriage", "children"],
    };
    required.push("report");
  }
  return { type: "object", additionalProperties: false, properties, required };
}

const SYSTEM = `You are an expert palmist for "PalmInsight", an entertainment palm-reading app.

STEP 1 — GATEKEEP. First decide whether this image clearly shows a human PALM: the INNER surface of a hand, palm and fingers facing the camera, with actual palm lines (creases) visible enough to read.
Set isPalm = false (and write a short, friendly reason) for ANYTHING that is not that, including: a person/scene/selfie, a face, an object, a hand holding a phone or cup, the BACK of a hand, a fist, a palm that is too dark/blurry/far/angled to see the lines, a drawing or diagram, or no hand at all. When isPalm is false, return an EMPTY lines array and DO NOT invent any reading.

STEP 2 — READ (only if isPalm is true). Read the ACTUAL lines visible in THIS palm — their length, depth, curvature, breaks, and branches — and base every interpretation on what you genuinely observe, so two different palms yield two different readings. Set reason to "".
Palm lines:
- life: curves around the thumb (energy, resilience, lifestyle)
- heart: top horizontal line (emotions, love)
- head: middle horizontal line (thinking, decisions)
- fate: vertical line toward the middle finger (career, life direction)
Write warm, vivid, specific, shareable interpretations (2-4 sentences each, second person). Confidence reflects how clearly each line is visible.

Output ONLY the requested JSON. Be a strict gatekeeper: it is far better to reject a non-palm than to fabricate a reading.`;

function userPrompt(keys: LineKey[], includeReport: boolean): string {
  const names = keys.join(", ");
  let p = `First decide if this image clearly shows a readable human palm. If not, set isPalm=false, give a short reason, and return an empty lines array. If it IS a clear palm, set isPalm=true and read these lines: ${names}. For each line give a pattern, an integer confidence (0-100), a one-line summary, and a 2-4 bullet interpretation based on what you actually observe in this specific palm.`;
  if (includeReport) {
    p += ` Also produce a premium "report" synthesized from the head, fate, heart and life lines (and overall hand shape) you observe in THIS palm. It must contain:
- highlights: { archetype (a catchy 2-4 word palm personality type), luckyNumber, luckyColor, luckyDay (a weekday) } — make these feel personal to this palm.
- destiny ("Your Destiny"): the big-picture life story.
- career ("Career & Success"): work strengths, ideal fields, a turning point.
- wealth ("Money & Wealth"): earning style, financial outlook, when prosperity peaks.
- love ("Love & Relationships"): emotional nature and how you connect.
- marriage ("Marriage & Partnership"): partnership timing, what a lasting bond looks like for you.
- children ("Family & Children"): family life, nurturing style, and what the lines hint about children.
Each section is a title plus a vivid 2-3 paragraph body array, warm and second-person. This is lighthearted entertainment — commit to specific, confident, shareable predictions.`;
  }
  return p;
}

// --- provider calls ---------------------------------------------------------

interface Attempt {
  provider: "anthropic" | "openai" | "gemini";
  model: string;
}

function chainFor(tier: "free" | "paid"): Attempt[] {
  const a = config.ai;
  const all: Attempt[] =
    tier === "paid"
      ? [
          { provider: "anthropic", model: a.anthropicPro },
          { provider: "openai", model: a.openaiPro },
          { provider: "gemini", model: a.geminiPro },
        ]
      : [
          { provider: "gemini", model: a.geminiCheap },
          { provider: "openai", model: a.openaiCheap },
          { provider: "anthropic", model: a.anthropicCheap },
        ];
  return all.filter(
    (x) =>
      (x.provider === "anthropic" && a.anthropicKey) ||
      (x.provider === "openai" && a.openaiKey) ||
      (x.provider === "gemini" && a.geminiKey)
  );
}

let _anthropic: Anthropic | null = null;
function anthropic(): Anthropic {
  if (!_anthropic) _anthropic = new Anthropic({ apiKey: config.ai.anthropicKey });
  return _anthropic;
}

/** Strip a data URL prefix → { mime, base64 }. */
function splitDataUrl(image: string): { mime: string; base64: string } {
  const m = image.match(/^data:([^;]+);base64,(.*)$/s);
  if (m) return { mime: m[1], base64: m[2] };
  return { mime: "image/jpeg", base64: image };
}

function parse(raw: string): VisionResult {
  // Models occasionally wrap JSON in prose or fences; extract the object.
  let text = raw.trim().replace(/^```(?:json)?/i, "").replace(/```$/i, "").trim();
  const start = text.indexOf("{");
  const end = text.lastIndexOf("}");
  if (start > 0 || end < text.length - 1) text = text.slice(start, end + 1);
  return VisionResultSchema.parse(JSON.parse(text));
}

async function callAnthropic(model: string, image: string, keys: LineKey[], report: boolean): Promise<VisionResult> {
  const { mime, base64 } = splitDataUrl(image);
  const res = await anthropic().messages.create({
    model,
    max_tokens: 4096,
    system: [{ type: "text", text: SYSTEM, cache_control: { type: "ephemeral" } }],
    output_config: { format: { type: "json_schema", schema: jsonSchema(report) } },
    messages: [
      {
        role: "user",
        content: [
          { type: "image", source: { type: "base64", media_type: mime as "image/jpeg", data: base64 } },
          { type: "text", text: userPrompt(keys, report) },
        ],
      },
    ],
  } as Anthropic.Messages.MessageCreateParamsNonStreaming);
  const block = res.content.find((b) => b.type === "text");
  return parse(block && "text" in block ? block.text : "");
}

async function callOpenAI(model: string, image: string, keys: LineKey[], report: boolean): Promise<VisionResult> {
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${config.ai.openaiKey}` },
    body: JSON.stringify({
      model,
      max_tokens: 4096,
      // Structured Outputs: force the EXACT response shape (otherwise the model
      // invents its own field names and parsing fails → silent fallback).
      response_format: {
        type: "json_schema",
        json_schema: { name: "palm_reading", strict: true, schema: jsonSchema(report) },
      },
      messages: [
        { role: "system", content: SYSTEM },
        {
          role: "user",
          content: [
            { type: "text", text: userPrompt(keys, report) },
            { type: "image_url", image_url: { url: image.startsWith("data:") ? image : `data:image/jpeg;base64,${image}` } },
          ],
        },
      ],
    }),
  });
  if (!res.ok) throw new Error(`OpenAI ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return parse(data.choices?.[0]?.message?.content ?? "");
}

async function callGemini(model: string, image: string, keys: LineKey[], report: boolean): Promise<VisionResult> {
  const { mime, base64 } = splitDataUrl(image);
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${config.ai.geminiKey}`;
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: SYSTEM }] },
      contents: [
        {
          role: "user",
          parts: [
            { text: userPrompt(keys, report) },
            { inlineData: { mimeType: mime, data: base64 } },
          ],
        },
      ],
      generationConfig: { responseMimeType: "application/json", responseSchema: jsonSchema(report), maxOutputTokens: 4096 },
    }),
  });
  if (!res.ok) throw new Error(`Gemini ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const text = data.candidates?.[0]?.content?.parts?.map((p: { text?: string }) => p.text).join("") ?? "";
  return parse(text);
}

async function callOne(a: Attempt, image: string, keys: LineKey[], report: boolean): Promise<VisionResult> {
  if (a.provider === "anthropic") return callAnthropic(a.model, image, keys, report);
  if (a.provider === "openai") return callOpenAI(a.model, image, keys, report);
  return callGemini(a.model, image, keys, report);
}

/**
 * Analyze the palm image and return interpretations for the given lines.
 * Walks the provider chain for the tier; returns null if AI is disabled or
 * every provider fails (callers then fall back to the deterministic engine).
 */
export async function analyzePalmImage(
  image: string,
  opts: { tier: "free" | "paid"; lines: LineKey[]; report?: boolean }
): Promise<VisionResult | null> {
  if (!aiEnabled || !image) return null;
  const chain = chainFor(opts.tier);
  let lastErr: unknown = null;
  for (const a of chain) {
    try {
      const result = await callOne(a, image, opts.lines, opts.report ?? false);
      // Keep only requested lines, clamp confidence.
      result.lines = result.lines
        .filter((l) => opts.lines.includes(l.key))
        .map((l) => ({ ...l, confidence: Math.round(Math.max(40, Math.min(99, l.confidence))) }));
      return result;
    } catch (err) {
      lastErr = err;
      // try next provider
    }
  }
  if (lastErr) console.error("[palmVision] all providers failed:", (lastErr as Error).message);
  return null;
}
